from .attribute_masking import AttributeMaskingPreTrainer
from .context_prediction import ContextPredictionPreTrainer
from .contextual import ContextualPreTrainer
from .edge_prediction import EdgePredictionPreTrainer
from .gpt_gnn import GPTGNNPreTrainer
from .graph_cl import GraphCLPreTrainer
from .info_max import InfoMaxPreTrainer
from .joao import JOAOPreTrainer
from .joao_v2 import JOAOv2PreTrainer
from .motif import MotifPreTrainer
from .graphmvp import GraphMVPPreTrainer
from .rgcl import RGCLPreTrainer
from .graphmae import GraphMAEPreTrainer
from .pretrainer import PreTrainer
